# Generated by Django 4.2.30 on 2026-09-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='coordenadas_poligono',
            field=models.TextField(blank=True, help_text='Coordenadas JSON del polígono', null=True),
        ),
    ]
