# Generated by Django 4.2.30 on 2026-09-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrenos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('notas_agricultor', models.TextField(blank=True, null=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('laboratorista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='terrenos.terreno')),
            ],
        ),
    ]
