# Generated by Django 4.2.30 on 2026-09-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudanalisis',
            name='cultivo_deseado',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudanalisis',
            name='modalidad',
            field=models.CharField(choices=[('VISITA', 'Solicitar Visita en Campo'), ('LLEVAR_MUESTRA', 'Llevar Muestra al Laboratorio')], default='VISITA', max_length=20),
        ),
    ]
