# Generated by Django 4.2.30 on 2026-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultivoIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('humedad_min', models.FloatField()),
                ('humedad_max', models.FloatField()),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('conductividad_min', models.FloatField()),
                ('conductividad_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('nitrogeno_min', models.FloatField()),
                ('nitrogeno_max', models.FloatField()),
                ('fosforo_min', models.FloatField()),
                ('fosforo_max', models.FloatField()),
                ('potasio_min', models.FloatField()),
                ('potasio_max', models.FloatField()),
            ],
        ),
    ]
