# Generated by Django 4.2.30 on 2026-10-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_espera_ia', models.IntegerField(default=30, help_text='Tiempo máximo de espera (segundos)')),
                ('accion_fallo_ia', models.CharField(choices=[('DB_LOCAL', 'Usar base de datos local automáticamente'), ('CANCELAR', 'Notificar al usuario y cancelar el análisis')], default='DB_LOCAL', max_length=50)),
                ('rango_ph_min', models.FloatField(default=0.0)),
                ('rango_ph_max', models.FloatField(default=14.0)),
                ('rango_n_min', models.FloatField(default=0.0)),
                ('rango_n_max', models.FloatField(default=1000.0)),
                ('rango_p_min', models.FloatField(default=0.0)),
                ('rango_p_max', models.FloatField(default=1000.0)),
                ('rango_k_min', models.FloatField(default=0.0)),
                ('rango_k_max', models.FloatField(default=1000.0)),
                ('rango_humedad_min', models.FloatField(default=0.0)),
                ('rango_humedad_max', models.FloatField(default=100.0)),
                ('rango_ce_min', models.FloatField(default=0.0)),
                ('rango_ce_max', models.FloatField(default=20.0)),
                ('rango_temp_min', models.FloatField(default=-10.0)),
                ('rango_temp_max', models.FloatField(default=60.0)),
            ],
        ),
    ]
