# Generated by Django 4.2.30 on 2026-09-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conductividad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ph', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('nitrogeno', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fosforo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('potasio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('diagnostico_ia', models.TextField(blank=True, help_text='JSON string con el reporte generado', null=True)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_resultado', to='solicitudes.solicitudanalisis')),
            ],
        ),
    ]
