CULTIVOS_HUILA = [
    {"nombre": "Café", "categoria": "Industrial", "clima": "Templado", "ph": "5.0 - 5.5", "humedad": "60% - 80%", "img": "fa-mug-hot"},
    {"nombre": "Cacao", "categoria": "Industrial", "clima": "Tropical", "ph": "6.0 - 7.5", "humedad": "70% - 90%", "img": "fa-seedling"},
    {"nombre": "Plátano", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 7.0", "humedad": "75% - 85%", "img": "fa-tree"},
    {"nombre": "Banano", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 7.0", "humedad": "75% - 85%", "img": "fa-tree"},
    {"nombre": "Maíz Tradicional", "categoria": "Cereal", "clima": "Templado/Cálido", "ph": "5.8 - 7.0", "humedad": "50% - 70%", "img": "fa-wheat-awn"},
    {"nombre": "Frijol", "categoria": "Leguminosa", "clima": "Templado", "ph": "5.5 - 6.5", "humedad": "50% - 60%", "img": "fa-leaf"},
    {"nombre": "Arroz Secano", "categoria": "Cereal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "80% - 90%", "img": "fa-wheat-awn"},
    {"nombre": "Caña Panelera", "categoria": "Industrial", "clima": "Tropical", "ph": "5.5 - 7.5", "humedad": "70% - 85%", "img": "fa-cubes"},
    {"nombre": "Aguacate Hass", "categoria": "Frutal", "clima": "Templado/Frío", "ph": "5.5 - 6.5", "humedad": "60% - 80%", "img": "fa-apple-whole"},
    {"nombre": "Cholupa", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "70% - 80%", "img": "fa-lemon"},
    {"nombre": "Granadilla", "categoria": "Frutal", "clima": "Templado", "ph": "5.5 - 6.8", "humedad": "70% - 85%", "img": "fa-lemon"},
    {"nombre": "Pitahaya", "categoria": "Frutal", "clima": "Cálido/Seco", "ph": "5.5 - 7.0", "humedad": "40% - 60%", "img": "fa-sun"},
    {"nombre": "Lulo", "categoria": "Frutal", "clima": "Templado", "ph": "5.5 - 6.5", "humedad": "75% - 85%", "img": "fa-apple-whole"},
    {"nombre": "Maracuyá", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "70% - 80%", "img": "fa-lemon"},
    {"nombre": "Tomate de Árbol", "categoria": "Frutal", "clima": "Frío", "ph": "5.5 - 6.5", "humedad": "70% - 85%", "img": "fa-apple-whole"},
    {"nombre": "Mora", "categoria": "Frutal", "clima": "Frío", "ph": "5.2 - 6.2", "humedad": "75% - 90%", "img": "fa-seedling"},
    {"nombre": "Gulupa", "categoria": "Frutal", "clima": "Templado", "ph": "5.5 - 6.5", "humedad": "75% - 85%", "img": "fa-lemon"},
    {"nombre": "Uchuva", "categoria": "Frutal", "clima": "Frío", "ph": "5.5 - 6.8", "humedad": "70% - 80%", "img": "fa-apple-whole"},
    {"nombre": "Yuca", "categoria": "Tubérculo", "clima": "Cálido", "ph": "5.5 - 7.5", "humedad": "50% - 70%", "img": "fa-carrot"},
    {"nombre": "Arracacha", "categoria": "Tubérculo", "clima": "Templado", "ph": "5.5 - 6.5", "humedad": "60% - 80%", "img": "fa-carrot"},
    {"nombre": "Papa", "categoria": "Tubérculo", "clima": "Frío", "ph": "5.0 - 6.0", "humedad": "70% - 85%", "img": "fa-potato"},
    {"nombre": "Guanábana", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "70% - 85%", "img": "fa-tree"},
    {"nombre": "Limón Tahití", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "60% - 80%", "img": "fa-lemon"},
    {"nombre": "Naranja", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "60% - 80%", "img": "fa-lemon"},
    {"nombre": "Mango", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 7.5", "humedad": "50% - 70%", "img": "fa-tree"},
    {"nombre": "Piña", "categoria": "Frutal", "clima": "Cálido", "ph": "4.5 - 5.5", "humedad": "60% - 75%", "img": "fa-sun"},
    {"nombre": "Papaya", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "70% - 85%", "img": "fa-tree"},
    {"nombre": "Sorgo", "categoria": "Cereal", "clima": "Cálido", "ph": "5.5 - 7.5", "humedad": "40% - 60%", "img": "fa-wheat-awn"},
    {"nombre": "Algodón", "categoria": "Industrial", "clima": "Cálido", "ph": "5.8 - 7.0", "humedad": "50% - 60%", "img": "fa-cloud"},
    {"nombre": "Tabaco", "categoria": "Industrial", "clima": "Cálido", "ph": "5.5 - 6.5", "humedad": "60% - 75%", "img": "fa-leaf"},
    {"nombre": "Cebolla Larga", "categoria": "Hortaliza", "clima": "Frío/Templado", "ph": "6.0 - 7.0", "humedad": "70% - 85%", "img": "fa-seedling"},
    {"nombre": "Cebolla Cabezona", "categoria": "Hortaliza", "clima": "Frío", "ph": "6.0 - 7.0", "humedad": "65% - 80%", "img": "fa-seedling"},
    {"nombre": "Tomate de Mesa", "categoria": "Hortaliza", "clima": "Templado", "ph": "6.0 - 6.8", "humedad": "60% - 75%", "img": "fa-apple-whole"},
    {"nombre": "Pimentón", "categoria": "Hortaliza", "clima": "Templado", "ph": "6.0 - 6.8", "humedad": "60% - 75%", "img": "fa-pepper-hot"},
    {"nombre": "Zanahoria", "categoria": "Hortaliza", "clima": "Frío", "ph": "5.8 - 6.8", "humedad": "70% - 80%", "img": "fa-carrot"},
    {"nombre": "Repollo", "categoria": "Hortaliza", "clima": "Frío", "ph": "6.0 - 6.8", "humedad": "75% - 85%", "img": "fa-leaf"},
    {"nombre": "Cilantro", "categoria": "Hortaliza", "clima": "Frío/Templado", "ph": "6.2 - 6.8", "humedad": "70% - 80%", "img": "fa-leaf"},
    {"nombre": "Lechuga", "categoria": "Hortaliza", "clima": "Frío", "ph": "6.0 - 7.0", "humedad": "75% - 85%", "img": "fa-leaf"},
    {"nombre": "Auyama", "categoria": "Hortaliza", "clima": "Cálido", "ph": "5.5 - 6.8", "humedad": "60% - 80%", "img": "fa-sun"},
    {"nombre": "Sandía", "categoria": "Frutal", "clima": "Cálido", "ph": "5.5 - 7.0", "humedad": "60% - 80%", "img": "fa-sun"}
]
